name: Pandoc

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "(    github.event_name == 'pull_request'
           && !contains(github.event.pull_request.body, '[skip ci]')
           && !contains(github.event.pull_request.body, '[skip docs]')
         )
         || contains(github.event.ref, 'pandoc')
         || contains(github.event.ref, 'master')"
    container:
      image: docker://pandoc/ubuntu-latex:2.11.4
      env:
          # TODO better to not need to hardcode this here
          TEXLIVE_HOME: /opt/texlive/texdir
      options: --entrypoint /bin/bash

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install additional TeX Live packages
        run: |
          tlmgr update --all --self
          tlmgr install tcolorbox environ selnolig

      - name: Generate PDF reference documentation
        run: cd pandoc && ./md2pdf reference

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: reference-pdf
          path: out/pandoc/scala3_reference.pdf
