name: Pandoc

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "(    github.event_name == 'pull_request'
           && !contains(github.event.pull_request.body, '[skip ci]')
           && !contains(github.event.pull_request.body, '[skip docs]')
         )
         || contains(github.event.ref, 'pandoc')
         || contains(github.event.ref, 'master')"

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Generate PDF reference documentation
        uses: docker://pandoc/ubuntu-latex:2.11.4
        with:
          #entrypoint: ls
          #args: -lR
          entrypoint: ./pandoc/md2pdf
          args: reference

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: reference-pdf
          path: out/pandoc/scala3_reference.pdf
